// 🔮 청소년 맞춤 타로 카드 78장 데이터
const TAROT_CARDS = [
  // ===== 메이저 아르카나 (0~21) =====
  {
    id: 0,
    name: "바보",
    nameEn: "The Fool",
    suit: "major",
    number: "0",
    emoji: "🌟",
    symbol: "✦",
    keywords: ["새로운 시작", "도전", "자유"],
    shortMsg: "새로운 시작의 에너지!",
    advice: "새로운 동아리나 공부를 시작하기 좋은 때예요. 실패를 두려워 말고 도전해 봐요! 지금 이 순간 망설이는 마음은 당연한 거예요. 하지만 첫 걸음을 떼는 용기가 가장 중요해요. 완벽하지 않아도 괜찮아요, 일단 시작해보는 것이 최고의 선택이에요!",
    light: "도전, 자유로움, 열린 마음",
    shadow: "무모함, 준비 부족"
  },
  {
    id: 1,
    name: "마법사",
    nameEn: "The Magician",
    suit: "major",
    number: "I",
    emoji: "✨",
    symbol: "⚡",
    keywords: ["잠재력", "재능", "실행력"],
    shortMsg: "당신 안에 재능이 가득해요!",
    advice: "준비물은 다 갖춰졌어요. 당신의 끼와 재능을 보여줄 기회예요! 오래 고민만 하지 말고 지금 가진 것들을 활용해 보세요. 내가 할 수 있다는 믿음이 모든 것을 가능하게 만들어줘요. 당신은 생각보다 훨씬 능력 있는 사람이에요!",
    light: "능력, 집중력, 자기 확신",
    shadow: "속임수, 자만"
  },
  {
    id: 2,
    name: "여사제",
    nameEn: "The High Priestess",
    suit: "major",
    number: "II",
    emoji: "🌙",
    symbol: "☽",
    keywords: ["직관", "내면의 목소리", "지혜"],
    shortMsg: "내 마음의 소리를 들어봐요!",
    advice: "지금 내 직감이 뭐라고 하나요? 머릿속으로 계산하기 전에 마음이 느끼는 것을 먼저 들어봐요. 조용히 나 자신과 대화하는 시간을 가져보세요. 일기를 쓰거나 혼자만의 시간을 갖는 것이 해결책을 찾는 데 도움이 될 거예요.",
    light: "직관, 자아 성찰, 신중함",
    shadow: "우유부단, 비밀 유지"
  },
  {
    id: 3,
    name: "여황제",
    nameEn: "The Empress",
    suit: "major",
    number: "III",
    emoji: "🌸",
    symbol: "♀",
    keywords: ["풍요", "창의력", "돌봄"],
    shortMsg: "주변을 사랑으로 채워봐요!",
    advice: "지금 내 주변을 따뜻하게 돌보는 것이 중요해요. 나를 포함해서 가족, 친구들과의 관계를 소중히 여겨봐요. 창의적인 활동(그림, 음악, 글쓰기 등)을 통해 감정을 표현해 보면 마음이 훨씬 가벼워질 거예요!",
    light: "풍요로움, 창의성, 따뜻한 마음",
    shadow: "의존성, 과잉 보호"
  },
  {
    id: 4,
    name: "황제",
    nameEn: "The Emperor",
    suit: "major",
    number: "IV",
    emoji: "👑",
    symbol: "♂",
    keywords: ["안정", "리더십", "계획"],
    shortMsg: "계획을 세우고 차근차근!",
    advice: "지금 필요한 건 확실한 계획과 규칙이에요. 공부 계획표를 만들거나 목표를 구체적으로 적어봐요. 작은 것부터 하나씩 해결해 나가다 보면 어느새 큰 목표도 이룰 수 있어요. 나만의 루틴을 만들어 보는 건 어떨까요?",
    light: "안정감, 책임감, 집중력",
    shadow: "고집, 지나친 통제"
  },
  {
    id: 5,
    name: "교황",
    nameEn: "The Hierophant",
    suit: "major",
    number: "V",
    emoji: "📚",
    symbol: "✝",
    keywords: ["배움", "조언", "전통"],
    shortMsg: "믿을 수 있는 어른에게 물어봐요!",
    advice: "지금 고민을 혼자 해결하려 하지 말고, 믿을 수 있는 선생님이나 부모님, 또는 상담 선생님께 도움을 요청해 봐요. 경험 많은 어른의 조언이 생각지 못한 길을 열어줄 수 있어요. 물어보는 건 약함이 아니라 지혜로움이에요!",
    light: "조언 수용, 배움, 협력",
    shadow: "지나친 의존, 융통성 부족"
  },
  {
    id: 6,
    name: "연인",
    nameEn: "The Lovers",
    suit: "major",
    number: "VI",
    emoji: "💫",
    symbol: "♡",
    keywords: ["관계", "선택", "조화"],
    shortMsg: "진심 어린 선택을 해봐요!",
    advice: "친구들 사이에서 조화가 필요해요. 내 마음이 끌리는 진심 어린 선택을 하세요. 관계에서 갈등이 있다면 솔직하게 대화해 보는 것이 최선이에요. 내가 어떤 관계를 원하는지, 내 가치관이 무엇인지 생각해 봐요.",
    light: "조화, 진심, 올바른 선택",
    shadow: "갈등, 우유부단함"
  },
  {
    id: 7,
    name: "전차",
    nameEn: "The Chariot",
    suit: "major",
    number: "VII",
    emoji: "⚡",
    symbol: "►",
    keywords: ["의지력", "승리", "추진력"],
    shortMsg: "포기하지 말고 앞으로 나아가요!",
    advice: "지금 힘들고 지쳐도 포기하지 마세요. 목표를 향해 꾸준히 나아가는 당신이 결국 이기게 되어 있어요. 잠깐 힘들어도 내 의지력을 믿어봐요. 한 걸음씩, 하루씩 최선을 다하다 보면 반드시 좋은 결과가 따라올 거예요!",
    light: "의지력, 집중, 승리",
    shadow: "공격성, 무리한 강행"
  },
  {
    id: 8,
    name: "힘",
    nameEn: "Strength",
    suit: "major",
    number: "VIII",
    emoji: "🦁",
    symbol: "∞",
    keywords: ["내면의 힘", "용기", "인내"],
    shortMsg: "부드럽지만 강한 내가 될 수 있어요!",
    advice: "진짜 용기는 두렵지 않은 게 아니라, 두려워도 한 발 내딛는 거예요. 지금 가장 필요한 건 나 자신을 믿는 내면의 힘이에요. 감정을 억누르기보다 차분하게 다스리는 연습을 해봐요. 당신은 생각보다 훨씬 강한 사람이에요!",
    light: "내면의 힘, 인내, 자기 조절",
    shadow: "자신감 부족, 과도한 억제"
  },
  {
    id: 9,
    name: "은둔자",
    nameEn: "The Hermit",
    suit: "major",
    number: "IX",
    emoji: "🔦",
    symbol: "△",
    keywords: ["성찰", "고독", "내면 탐구"],
    shortMsg: "잠깐 혼자만의 시간을 가져봐요!",
    advice: "모든 걸 다 잘할 필요 없어요. 지금은 조용히 내 마음을 들여다볼 시간이 필요해요. SNS와 잠깐 거리를 두고 나 자신과 대화해 보세요. 일기 쓰기, 산책, 독서처럼 혼자 할 수 있는 활동이 생각을 정리하는 데 도움이 될 거예요.",
    light: "자아 성찰, 내면의 지혜, 평온",
    shadow: "고립, 지나친 내향"
  },
  {
    id: 10,
    name: "운명의 수레바퀴",
    nameEn: "Wheel of Fortune",
    suit: "major",
    number: "X",
    emoji: "🎡",
    symbol: "⊕",
    keywords: ["변화", "기회", "운명"],
    shortMsg: "변화가 새로운 기회가 될 거예요!",
    advice: "갑작스러운 환경 변화(반 배정, 전학 등)가 예상치 못한 행운이 될 수 있어요. 지금 힘든 변화라도 결국 더 좋은 방향으로 흘러가게 되어 있어요. 변화를 두려워하지 말고 새로운 가능성으로 받아들여 봐요!",
    light: "기회, 긍정적 변화, 행운",
    shadow: "예측 불가, 불안감"
  },
  {
    id: 11,
    name: "정의",
    nameEn: "Justice",
    suit: "major",
    number: "XI",
    emoji: "⚖️",
    symbol: "♎",
    keywords: ["공정함", "진실", "균형"],
    shortMsg: "정직하게 대처하면 해결돼요!",
    advice: "지금 상황을 있는 그대로 솔직하게 바라봐요. 내가 잘못한 부분이 있다면 인정하고, 억울한 부분이 있다면 차분하게 말로 표현해 보세요. 공정하고 정직한 태도가 결국 가장 좋은 결과를 만들어요.",
    light: "공정함, 정직, 균형",
    shadow: "지나친 비판, 냉정함"
  },
  {
    id: 12,
    name: "매달린 남자",
    nameEn: "The Hanged Man",
    suit: "major",
    number: "XII",
    emoji: "🙃",
    symbol: "▽",
    keywords: ["새로운 관점", "기다림", "수용"],
    shortMsg: "다르게 생각하면 답이 보여요!",
    advice: "잠시 멈춰서 생각해도 괜찮아요. 다르게 생각하면 해결책이 보일 거예요. 지금 상황을 다른 각도에서 바라보면 어떨까요? 빠른 해결보다 충분히 생각하고 기다리는 것이 오히려 더 나은 답을 줄 수 있어요.",
    light: "새로운 시각, 수용, 인내",
    shadow: "정체감, 희생"
  },
  {
    id: 13,
    name: "죽음",
    nameEn: "Death",
    suit: "major",
    number: "XIII",
    emoji: "🦋",
    symbol: "☽",
    keywords: ["끝과 새 시작", "변화", "전환"],
    shortMsg: "힘든 시간이 끝나고 새 출발이 시작돼요!",
    advice: "무서운 일이 생기는 게 아니에요! 힘들었던 숙제나 고민이 끝나고 완전히 새로운 기분이 시작되는 시기예요. 오래된 습관이나 나에게 맞지 않는 것들을 내려놓을 준비가 되었어요. 이 변화는 더 좋은 나로 성장하는 과정이에요!",
    light: "새로운 시작, 변화, 성장",
    shadow: "저항, 변화에 대한 두려움"
  },
  {
    id: 14,
    name: "절제",
    nameEn: "Temperance",
    suit: "major",
    number: "XIV",
    emoji: "🌈",
    symbol: "☯",
    keywords: ["균형", "조화", "인내"],
    shortMsg: "천천히, 균형 있게 나아가요!",
    advice: "급하게 서두르지 않아도 괜찮아요. 공부도, 관계도, 모든 것에 균형이 중요해요. 너무 한쪽에만 치우치지 말고 여러 가지를 골고루 챙겨봐요. 쉬는 것도 열심히 하는 것만큼 중요하다는 걸 잊지 마세요!",
    light: "균형, 조화, 인내, 중용",
    shadow: "지나친 절제, 무감각"
  },
  {
    id: 15,
    name: "악마",
    nameEn: "The Devil",
    suit: "major",
    number: "XV",
    emoji: "🔓",
    symbol: "♄",
    keywords: ["속박", "유혹", "자유"],
    shortMsg: "나를 묶고 있는 것에서 벗어나요!",
    advice: "지금 나를 힘들게 하는 무언가에 너무 얽매여 있지 않나요? SNS 중독, 나쁜 습관, 독한 관계 등 나를 힘들게 만드는 것들을 하나씩 점검해 봐요. 벗어나는 것이 어렵게 느껴지지만, 그건 충분히 가능해요. 상담 선생님과 이야기해 봐요!",
    light: "자유 의지, 변화, 용기",
    shadow: "중독, 속박, 부정적 패턴"
  },
  {
    id: 16,
    name: "탑",
    nameEn: "The Tower",
    suit: "major",
    number: "XVI",
    emoji: "⚡",
    symbol: "↯",
    keywords: ["갑작스러운 변화", "각성", "재건"],
    shortMsg: "충격적인 변화도 새 출발의 기회예요!",
    advice: "갑자기 무언가 무너지는 것 같은 기분이 드나요? 그게 관계든, 계획이든 괜찮아요. 가끔 모든 게 흔들려야 더 단단한 기반을 다시 세울 수 있어요. 지금 힘든 상황은 더 강한 나를 만드는 과정이에요!",
    light: "각성, 재건, 진실 직면",
    shadow: "갑작스러운 혼란, 충격"
  },
  {
    id: 17,
    name: "별",
    nameEn: "The Star",
    suit: "major",
    number: "XVII",
    emoji: "⭐",
    symbol: "★",
    keywords: ["희망", "꿈", "치유"],
    shortMsg: "당신의 꿈은 반드시 이루어질 거예요!",
    advice: "하고 싶은 일이 있다면 구체적인 목표를 세워보세요. 긍정적인 결과가 기다려요. 지금 힘들어도 희망을 잃지 마세요. 작게라도 꿈을 향해 움직이다 보면 언젠가 반짝이는 별처럼 빛나는 순간이 찾아올 거예요!",
    light: "희망, 꿈, 회복, 영감",
    shadow: "비현실적 기대, 허탈감"
  },
  {
    id: 18,
    name: "달",
    nameEn: "The Moon",
    suit: "major",
    number: "XVIII",
    emoji: "🌕",
    symbol: "☾",
    keywords: ["불안", "직관", "잠재의식"],
    shortMsg: "두려움을 직면하면 사라져요!",
    advice: "지금 막연한 불안이나 두려움이 있나요? 그 감정을 피하지 말고 '이게 뭐지?'라고 직접 들여다봐요. 막연한 걱정은 대부분 실제로는 그렇게 무섭지 않아요. 신뢰할 수 있는 친구나 어른에게 솔직히 털어놓으면 훨씬 가벼워질 거예요.",
    light: "직관, 감수성, 내면 탐구",
    shadow: "불안, 혼란, 두려움"
  },
  {
    id: 19,
    name: "태양",
    nameEn: "The Sun",
    suit: "major",
    number: "XIX",
    emoji: "☀️",
    symbol: "☀",
    keywords: ["성공", "행복", "활력"],
    shortMsg: "최고로 빛나는 시간이 왔어요!",
    advice: "지금 하는 일이 잘 풀리고 보람을 느낄 거예요. 밝은 에너지를 마음껏 즐기세요! 자신감을 가지고 하고 싶은 일에 도전해 봐요. 주변 사람들과 이 기쁨을 함께 나누면 더욱 빛날 거예요. 지금 이 순간이 정말 소중한 시간이에요!",
    light: "성공, 행복, 자신감, 활력",
    shadow: "자만, 순진함"
  },
  {
    id: 20,
    name: "심판",
    nameEn: "Judgement",
    suit: "major",
    number: "XX",
    emoji: "🎺",
    symbol: "♾",
    keywords: ["새로운 각성", "반성", "재탄생"],
    shortMsg: "진짜 나를 발견하는 순간이 왔어요!",
    advice: "지금까지의 나를 돌아보고 새롭게 시작할 기회예요. 과거의 실수나 후회를 거울로 삼아 더 나은 내가 되어봐요. 나 자신을 용서하고, 새로운 나를 만날 준비가 되었어요. 지금이 바로 그 순간이에요!",
    light: "각성, 자기 수용, 재탄생",
    shadow: "자기 비판, 죄책감"
  },
  {
    id: 21,
    name: "세계",
    nameEn: "The World",
    suit: "major",
    number: "XXI",
    emoji: "🌍",
    symbol: "○",
    keywords: ["완성", "성취", "통합"],
    shortMsg: "한 단계를 완전히 완성했어요!",
    advice: "큰 목표를 이루거나 중요한 단계를 마무리하는 시기예요. 이 성취감을 충분히 즐기고 다음 단계를 준비해 봐요. 당신이 지금까지 얼마나 성장했는지 스스로 인정해 줘요. 멋진 마무리가 새로운 여정의 시작이 돼요!",
    light: "완성, 성취, 통합, 성공",
    shadow: "완성 지연, 정체"
  },

  // ===== 마이너 아르카나 - 컵 (Cups) =====
  {
    id: 22,
    name: "에이스 컵",
    nameEn: "Ace of Cups",
    suit: "cups",
    number: "A",
    emoji: "💧",
    symbol: "♡",
    keywords: ["새로운 감정", "설렘", "우정"],
    shortMsg: "새로운 우정과 설렘이 시작돼요!",
    advice: "새로운 우정이나 설레는 감정이 시작될 징조예요. 마음을 열고 주변 사람들에게 다가가 봐요. 먼저 다가가는 것이 두렵더라도 작은 미소 하나가 새로운 관계의 시작이 될 수 있어요. 진심 어린 마음으로 대하면 좋은 인연이 생길 거예요!",
    light: "새로운 감정, 개방성, 창의력",
    shadow: "감정 억압, 기회 거절"
  },
  {
    id: 23,
    name: "컵 2",
    nameEn: "Two of Cups",
    suit: "cups",
    number: "2",
    emoji: "💑",
    symbol: "♡♡",
    keywords: ["단짝", "소울메이트", "연결"],
    shortMsg: "마음 맞는 단짝 친구를 만나요!",
    advice: "마음이 잘 맞는 단짝 친구(소울메이트)를 만나게 돼요. 서로 존중하고 배려하는 관계가 만들어지고 있어요. 지금 가까이에 있는 사람에게 솔직한 마음을 표현해 봐요. 진정한 우정은 솔직함에서 시작해요!",
    light: "우정, 상호 이해, 연결",
    shadow: "오해, 관계 불균형"
  },
  {
    id: 24,
    name: "컵 3",
    nameEn: "Three of Cups",
    suit: "cups",
    number: "3",
    emoji: "🎉",
    symbol: "♡♡♡",
    keywords: ["축하", "우정", "즐거움"],
    shortMsg: "친구들과 신나는 일이 생겨요!",
    advice: "친구들과의 즐거운 모임이나 축하할 일이 생길 거예요. 함께 나누는 기쁨이 혼자 느끼는 것보다 훨씬 크고 소중해요. 고민을 잠시 내려놓고 친구들과 즐거운 시간을 보내봐요. 좋은 추억이 에너지가 될 거예요!",
    light: "축하, 우정, 협력, 즐거움",
    shadow: "과도한 파티, 방탕함"
  },
  {
    id: 25,
    name: "컵 4",
    nameEn: "Four of Cups",
    suit: "cups",
    number: "4",
    emoji: "😔",
    symbol: "♡",
    keywords: ["권태", "성찰", "재고"],
    shortMsg: "주변의 좋은 것들을 다시 봐요!",
    advice: "지금 뭔가 지루하고 무기력한 기분인가요? 주변에 이미 좋은 것들이 많은데 못 보고 있는 건 아닐까요? 작은 것에서 감사함을 찾아봐요. 당연하게 여기던 것들의 소중함을 다시 느껴보면 기분이 달라질 거예요.",
    light: "성찰, 재고, 내면 탐구",
    shadow: "무관심, 놓친 기회"
  },
  {
    id: 26,
    name: "컵 5",
    nameEn: "Five of Cups",
    suit: "cups",
    number: "5",
    emoji: "😢",
    symbol: "♡",
    keywords: ["슬픔", "후회", "희망"],
    shortMsg: "곁에 남은 소중한 것을 봐요!",
    advice: "지나간 실수나 상처에 너무 매달리지 말고, 곁에 남은 소중한 것을 봐요. 지나간 일은 바꿀 수 없지만, 지금 이 순간은 달라질 수 있어요. 슬픔을 충분히 느끼되, 언제까지나 거기 머물지는 말아요. 여전히 네 편인 사람들이 곁에 있어요!",
    light: "감정 표현, 치유, 전진",
    shadow: "슬픔, 후회, 집착"
  },
  {
    id: 27,
    name: "컵 6",
    nameEn: "Six of Cups",
    suit: "cups",
    number: "6",
    emoji: "🌼",
    symbol: "♡",
    keywords: ["추억", "순수함", "나눔"],
    shortMsg: "따뜻한 추억이 힘이 돼요!",
    advice: "행복했던 과거의 기억들이 지금의 나에게 힘을 줄 거예요. 어릴 때 좋아했던 것들, 즐거웠던 기억을 떠올려봐요. 그 순수한 감정이 지금 고민의 해답을 줄 수도 있어요. 주변 사람들과 따뜻한 추억을 만들어 보세요!",
    light: "그리움, 나눔, 순수함",
    shadow: "과거 집착, 미성숙"
  },
  {
    id: 28,
    name: "컵 7",
    nameEn: "Seven of Cups",
    suit: "cups",
    number: "7",
    emoji: "🌈",
    symbol: "♡",
    keywords: ["꿈", "선택", "환상"],
    shortMsg: "현실적인 목표를 정해봐요!",
    advice: "꿈과 상상력이 풍부한 건 좋지만, 너무 환상에만 빠져 있으면 현실을 놓칠 수 있어요. 원하는 것들 중에서 정말 중요한 것 하나를 골라서 집중해 봐요. 구체적인 계획을 세우면 꿈이 현실이 될 수 있어요!",
    light: "상상력, 가능성, 꿈",
    shadow: "환상, 우유부단, 산만함"
  },
  {
    id: 29,
    name: "컵 8",
    nameEn: "Eight of Cups",
    suit: "cups",
    number: "8",
    emoji: "🚶",
    symbol: "♡",
    keywords: ["이별", "성장", "새 출발"],
    shortMsg: "더 이상 맞지 않는 것은 놓아줘요!",
    advice: "지금 더 이상 나에게 맞지 않는 것들을 용기 있게 내려놓을 시기예요. 친구 관계든, 습관이든 나를 행복하게 만들지 않는 것들을 돌아봐요. 익숙한 것을 떠나는 건 무섭지만, 더 좋은 것을 향해 나아가는 용기예요!",
    light: "성장, 용기, 새 출발",
    shadow: "포기, 현실 도피"
  },
  {
    id: 30,
    name: "컵 9",
    nameEn: "Nine of Cups",
    suit: "cups",
    number: "9",
    emoji: "🌟",
    symbol: "♡",
    keywords: ["만족", "소원 성취", "행복"],
    shortMsg: "원하는 것이 이루어질 거예요!",
    advice: "소원 카드예요! 지금 마음속으로 바라는 것들이 이루어질 조짐이 보여요. 감사하는 마음으로 하루하루를 보내봐요. 행복은 멀리 있지 않고 지금 이 순간에 있어요. 오늘 하루 좋아하는 것을 해봐요!",
    light: "만족, 소원 성취, 행복, 감사",
    shadow: "자만, 욕심"
  },
  {
    id: 31,
    name: "컵 10",
    nameEn: "Ten of Cups",
    suit: "cups",
    number: "10",
    emoji: "🏡",
    symbol: "♡",
    keywords: ["행복한 관계", "가족", "조화"],
    shortMsg: "주변과의 관계가 행복해져요!",
    advice: "가족이나 친구들과의 관계가 따뜻하고 행복한 시기예요. 지금 주변에 있는 소중한 사람들에게 감사함을 표현해 봐요. 함께할 때 더 빛나는 것들이 있어요. 이 행복한 에너지를 나누면 더 커진답니다!",
    light: "행복, 조화, 사랑, 완성",
    shadow: "이상화, 현실과의 괴리"
  },
  {
    id: 32,
    name: "페이지 컵",
    nameEn: "Page of Cups",
    suit: "cups",
    number: "P",
    emoji: "🐟",
    symbol: "♡",
    keywords: ["감성", "창의력", "메시지"],
    shortMsg: "창의적인 아이디어를 표현해봐요!",
    advice: "감성적이고 창의적인 아이디어가 넘치는 시기예요. 글쓰기, 그림, 음악 등 예술적인 표현을 통해 마음을 드러내봐요. 꿈이나 상상을 통해 중요한 힌트를 얻을 수도 있어요. 자유롭게 상상하고 표현해 봐요!",
    light: "감성, 창의력, 열린 마음",
    shadow: "감정적 미성숙, 공상"
  },
  {
    id: 33,
    name: "나이트 컵",
    nameEn: "Knight of Cups",
    suit: "cups",
    number: "N",
    emoji: "🐎",
    symbol: "♡",
    keywords: ["낭만", "이상주의", "감성"],
    shortMsg: "마음을 표현할 용기를 내봐요!",
    advice: "감성적이고 따뜻한 마음이 가득한 시기예요. 좋아하는 사람에게 마음을 표현하거나, 하고 싶은 말을 해봐요. 다만 감정에만 휩쓸리지 말고 현실도 함께 고려해 봐요. 진심을 담아 행동하면 좋은 결과가 따라올 거예요!",
    light: "낭만, 감성, 이상주의",
    shadow: "비현실적, 변덕스러움"
  },
  {
    id: 34,
    name: "퀸 컵",
    nameEn: "Queen of Cups",
    suit: "cups",
    number: "Q",
    emoji: "👸",
    symbol: "♡",
    keywords: ["공감", "배려", "직관"],
    shortMsg: "나 자신도 돌봐주는 것이 중요해요!",
    advice: "주변 사람들을 잘 공감하고 돌봐주는 당신이지만, 자기 자신도 챙기는 것을 잊지 마세요. 다른 사람의 감정에 너무 흔들리지 말고, 내 감정도 소중히 여겨봐요. 경계를 설정하는 것도 배려예요!",
    light: "공감, 돌봄, 직관, 감성",
    shadow: "지나친 감정 이입, 자기 방치"
  },
  {
    id: 35,
    name: "킹 컵",
    nameEn: "King of Cups",
    suit: "cups",
    number: "K",
    emoji: "🤴",
    symbol: "♡",
    keywords: ["감정 조절", "균형", "지혜"],
    shortMsg: "감정을 지혜롭게 다스려봐요!",
    advice: "감정을 차분하게 조절하면서도 따뜻한 마음을 유지하는 것이 중요한 시기예요. 화나거나 속상할 때 바로 반응하기보다 잠깐 숨을 고르고 대처해 봐요. 감정적으로 성숙해지는 과정이 지금 일어나고 있어요!",
    light: "감정 균형, 지혜, 성숙함",
    shadow: "감정 억압, 변덕"
  },

  // ===== 마이너 아르카나 - 완드 (Wands) =====
  {
    id: 36,
    name: "에이스 완드",
    nameEn: "Ace of Wands",
    suit: "wands",
    number: "A",
    emoji: "🔥",
    symbol: "⊕",
    keywords: ["시작", "열정", "영감"],
    shortMsg: "새로운 프로젝트 시작하기 최고의 때!",
    advice: "새로운 프로젝트나 공부 계획을 세우기에 가장 좋은 시기입니다. 하고 싶은 게 생겼다면 지금 당장 시작해봐요! 작은 것부터 시작해도 충분해요. 열정이 불처럼 타오를 때 바로 행동으로 옮기는 것이 중요해요!",
    light: "열정, 시작, 영감, 창의력",
    shadow: "조급함, 방향 상실"
  },
  {
    id: 37,
    name: "완드 2",
    nameEn: "Two of Wands",
    suit: "wands",
    number: "2",
    emoji: "🌍",
    symbol: "⊕",
    keywords: ["계획", "미래 비전", "결정"],
    shortMsg: "미래를 구체적으로 그려봐요!",
    advice: "지금 눈앞의 것만 보지 말고 더 넓게, 더 멀리 바라봐요. 1년 후, 5년 후 내가 어떤 사람이 되고 싶은지 생각해 봐요. 꿈이 구체적일수록 이루어질 가능성이 높아요. 오늘 작은 계획 하나를 세워봐요!",
    light: "비전, 계획, 결단력",
    shadow: "우유부단, 현실 도피"
  },
  {
    id: 38,
    name: "완드 3",
    nameEn: "Three of Wands",
    suit: "wands",
    number: "3",
    emoji: "⛵",
    symbol: "⊕",
    keywords: ["기다림", "확장", "도전"],
    shortMsg: "준비가 됐어요, 넓은 세상으로!",
    advice: "노력의 결과가 서서히 나타나기 시작하는 때예요. 아직 완전히 펼쳐지지 않았지만 좋은 신호들이 보여요. 조금 더 기다리면서 준비를 더 철저히 해봐요. 더 넓은 기회를 향해 눈을 열어봐요!",
    light: "확장, 기다림, 준비",
    shadow: "지연, 조급함"
  },
  {
    id: 39,
    name: "완드 4",
    nameEn: "Four of Wands",
    suit: "wands",
    number: "4",
    emoji: "🎊",
    symbol: "⊕",
    keywords: ["축하", "안정", "성취"],
    shortMsg: "작은 성취를 마음껏 축하해요!",
    advice: "지금까지의 노력에 대한 보상이 시작되고 있어요. 작은 성공이라도 충분히 축하하고 기뻐해봐요. 주변 사람들과 함께 이 기쁨을 나눠봐요. 안정적인 기반 위에서 더 큰 꿈을 향해 나아갈 수 있어요!",
    light: "축하, 안정, 성취, 기쁨",
    shadow: "불안정, 이른 축하"
  },
  {
    id: 40,
    name: "완드 5",
    nameEn: "Five of Wands",
    suit: "wands",
    number: "5",
    emoji: "⚔️",
    symbol: "⊕",
    keywords: ["경쟁", "갈등", "도전"],
    shortMsg: "건강한 경쟁으로 성장해요!",
    advice: "지금 주변에 의견 충돌이나 경쟁이 있나요? 갈등을 피하기보다 건강한 토론과 경쟁을 통해 서로 성장하는 기회로 만들어봐요. 내 의견을 당당하게 표현하되, 상대방의 말도 귀 기울여 들어봐요!",
    light: "경쟁, 다양성, 토론",
    shadow: "갈등, 혼란, 방해"
  },
  {
    id: 41,
    name: "완드 6",
    nameEn: "Six of Wands",
    suit: "wands",
    number: "6",
    emoji: "🏆",
    symbol: "⊕",
    keywords: ["승리", "인정", "성취"],
    shortMsg: "노력한 만큼 인정받아요!",
    advice: "노력한 만큼 성적이나 결과가 잘 나와서 주변의 인정을 받게 돼요. 그동안 열심히 해온 것들이 빛을 발하는 시기예요. 자신을 칭찬해주고, 이 성취를 발판 삼아 더 높이 나아봐요!",
    light: "승리, 인정, 자신감",
    shadow: "자만, 지나친 의존"
  },
  {
    id: 42,
    name: "완드 7",
    nameEn: "Seven of Wands",
    suit: "wands",
    number: "7",
    emoji: "🛡️",
    symbol: "⊕",
    keywords: ["방어", "지속", "용기"],
    shortMsg: "내 입장을 당당히 지켜봐요!",
    advice: "주변의 압박이나 어려움에도 내 신념을 지키는 것이 중요해요. 옳다고 생각하는 것을 위해 용기 있게 서 있어봐요. 다른 사람들의 시선이 두려워도 내 가치관을 잃지 마세요. 당신이 서 있는 곳이 틀리지 않았어요!",
    light: "용기, 방어, 지속력",
    shadow: "완고함, 지나친 방어"
  },
  {
    id: 43,
    name: "완드 8",
    nameEn: "Eight of Wands",
    suit: "wands",
    number: "8",
    emoji: "🚀",
    symbol: "⊕",
    keywords: ["빠른 진전", "소통", "행동"],
    shortMsg: "빠르게 움직일 때예요!",
    advice: "지금 일들이 빠르게 진행되고 있어요. 기회가 왔을 때 망설이지 말고 빠르게 행동해봐요. 좋은 소식이나 기회가 생길 수 있으니 열린 마음으로 받아들여요. 소통과 연락을 활발히 해봐요!",
    light: "빠른 진전, 소통, 행동",
    shadow: "서두름, 산만함"
  },
  {
    id: 44,
    name: "완드 9",
    nameEn: "Nine of Wands",
    suit: "wands",
    number: "9",
    emoji: "🤕",
    symbol: "⊕",
    keywords: ["회복력", "지침", "방어"],
    shortMsg: "충분히 쉬어야 다시 달릴 수 있어요!",
    advice: "많이 지쳐 있네요. 무리해서 버티기보다 회복할 시간이 필요해요. 잠깐 멈추고 재충전하는 것이 더 멀리 가는 길이에요. 충분한 수면, 맛있는 음식, 좋아하는 활동으로 배터리를 채워봐요. 쉬는 것도 실력이에요!",
    light: "회복력, 끈기, 경험",
    shadow: "소진, 과도한 경계심"
  },
  {
    id: 45,
    name: "완드 10",
    nameEn: "Ten of Wands",
    suit: "wands",
    number: "10",
    emoji: "😓",
    symbol: "⊕",
    keywords: ["과부하", "책임감", "완성"],
    shortMsg: "혼자 다 짊어지지 않아도 돼요!",
    advice: "지금 너무 많은 것을 혼자 짊어지고 있는 건 아닌가요? 도움을 요청하는 것은 약함이 아니에요. 주변에 믿을 수 있는 사람에게 솔직하게 힘들다고 말해봐요. 짐을 나누면 훨씬 가벼워질 거예요!",
    light: "책임감, 완성, 헌신",
    shadow: "과부하, 번아웃"
  },
  {
    id: 46,
    name: "페이지 완드",
    nameEn: "Page of Wands",
    suit: "wands",
    number: "P",
    emoji: "🌱",
    symbol: "⊕",
    keywords: ["탐험", "열정", "자유"],
    shortMsg: "새로운 것에 도전하는 용기!",
    advice: "새로운 것을 탐험하고 배우는 것을 두려워하지 말아요. 지금 관심 있는 것을 마음껏 탐구해봐요. 완벽하지 않아도 괜찮아요, 경험이 쌓이면서 실력이 늘어나요. 호기심을 잃지 마세요!",
    light: "탐험, 호기심, 열정",
    shadow: "무모함, 일관성 부족"
  },
  {
    id: 47,
    name: "나이트 완드",
    nameEn: "Knight of Wands",
    suit: "wands",
    number: "N",
    emoji: "🐎",
    symbol: "⊕",
    keywords: ["행동", "추진력", "모험"],
    shortMsg: "계획보다 행동이 먼저예요!",
    advice: "계획만 하기보다 일단 행동으로 옮기는 추진력이 필요할 때입니다. 너무 많이 생각하다 보면 오히려 기회를 놓칠 수 있어요. 완벽하지 않아도 지금 시작하는 것이 중요해요. 일단 해보고 수정하면 돼요!",
    light: "행동력, 추진력, 모험심",
    shadow: "무모함, 충동성"
  },
  {
    id: 48,
    name: "퀸 완드",
    nameEn: "Queen of Wands",
    suit: "wands",
    number: "Q",
    emoji: "👸",
    symbol: "⊕",
    keywords: ["자신감", "리더십", "활력"],
    shortMsg: "당당하고 활기차게 나를 표현해봐요!",
    advice: "자신감을 가지고 내 매력을 발산할 때예요. 남들이 어떻게 볼까 걱정하기보다 내가 원하는 것을 당당하게 표현해봐요. 주변에 긍정적인 에너지를 나눠주면 더 많은 사람들이 당신 주변에 모일 거예요!",
    light: "자신감, 활력, 리더십",
    shadow: "지배적, 질투"
  },
  {
    id: 49,
    name: "킹 완드",
    nameEn: "King of Wands",
    suit: "wands",
    number: "K",
    emoji: "🤴",
    symbol: "⊕",
    keywords: ["리더십", "비전", "결단력"],
    shortMsg: "비전을 가지고 앞장서봐요!",
    advice: "내 꿈과 비전을 향해 당당하게 나아가는 시기예요. 주변 사람들에게 긍정적인 영향을 미치고 함께 이끌어가는 리더가 될 수 있어요. 큰 그림을 그리고 작은 것부터 실천해봐요!",
    light: "비전, 리더십, 결단력",
    shadow: "독재, 지나친 자신감"
  },

  // ===== 마이너 아르카나 - 소드 (Swords) =====
  {
    id: 50,
    name: "에이스 소드",
    nameEn: "Ace of Swords",
    suit: "swords",
    number: "A",
    emoji: "⚔️",
    symbol: "△",
    keywords: ["명확함", "돌파구", "진실"],
    shortMsg: "복잡한 머릿속이 시원하게 정리돼요!",
    advice: "복잡한 머릿속이 정리되고 확실한 해결책을 찾게 될 거예요. 지금 고민하는 문제의 핵심을 파악하는 힘이 생기고 있어요. 솔직하고 직접적으로 표현하면 오해가 풀릴 거예요. 진실을 직면하는 용기를 내봐요!",
    light: "명확함, 진실, 돌파구",
    shadow: "냉혹함, 갈등"
  },
  {
    id: 51,
    name: "소드 2",
    nameEn: "Two of Swords",
    suit: "swords",
    number: "2",
    emoji: "😶",
    symbol: "△",
    keywords: ["갈등", "결정 장애", "균형"],
    shortMsg: "눈을 뜨고 현실을 직면해봐요!",
    advice: "어려운 결정을 회피하고 있지 않나요? 눈을 감고 있다고 문제가 사라지지 않아요. 필요한 정보를 모으고 믿을 수 있는 사람과 대화해봐요. 결정을 내리는 것이 두렵더라도, 결국 선택을 해야 앞으로 나갈 수 있어요!",
    light: "균형, 중립, 고민",
    shadow: "회피, 결정 장애"
  },
  {
    id: 52,
    name: "소드 3",
    nameEn: "Three of Swords",
    suit: "swords",
    number: "3",
    emoji: "💔",
    symbol: "△",
    keywords: ["상처", "슬픔", "치유"],
    shortMsg: "아픔을 느끼고 치유가 시작돼요!",
    advice: "지금 마음이 많이 아프고 상처받은 상태인가요? 그 감정을 억누르지 말고 충분히 느껴봐요. 울어도 괜찮아요. 아픔을 직면해야 치유가 시작돼요. 가까운 친구나 상담 선생님에게 솔직하게 털어놓아봐요.",
    light: "감정 표현, 치유, 회복",
    shadow: "슬픔, 상처, 배신"
  },
  {
    id: 53,
    name: "소드 4",
    nameEn: "Four of Swords",
    suit: "swords",
    number: "4",
    emoji: "😴",
    symbol: "△",
    keywords: ["휴식", "회복", "재충전"],
    shortMsg: "지금은 쉬는 것이 최우선이에요!",
    advice: "지금은 휴식이 최우선! 충분히 자고 쉬어야 다시 시작할 수 있어요. 억지로 힘을 내려 하지 말고 몸과 마음이 회복할 시간을 줘봐요. 잠을 충분히 자고, 좋아하는 음악을 듣고, 아무 생각 없이 쉬어봐요. 그것이 지금 가장 필요한 일이에요!",
    light: "휴식, 회복, 명상",
    shadow: "고립, 무기력"
  },
  {
    id: 54,
    name: "소드 5",
    nameEn: "Five of Swords",
    suit: "swords",
    number: "5",
    emoji: "😤",
    symbol: "△",
    keywords: ["갈등", "패배", "이기심"],
    shortMsg: "이기는 것보다 관계가 더 중요해요!",
    advice: "지금 승패보다 관계가 더 중요하지 않을까요? 모든 것에서 이기려 하다가 소중한 사람을 잃을 수 있어요. 가끔은 지는 것처럼 보여도 진심 어린 화해가 더 큰 승리예요. 먼저 손을 내밀어봐요!",
    light: "현실 직시, 반성",
    shadow: "갈등, 자기중심적"
  },
  {
    id: 55,
    name: "소드 6",
    nameEn: "Six of Swords",
    suit: "swords",
    number: "6",
    emoji: "⛵",
    symbol: "△",
    keywords: ["전환", "이동", "치유"],
    shortMsg: "힘든 시간이 지나가고 있어요!",
    advice: "힘들었던 상황에서 점차 벗어나고 있어요. 아직 완전히 편하진 않지만 분명 나아지고 있어요. 조금씩 앞으로 나아가는 것만으로도 충분해요. 더 평화로운 곳으로 향하고 있다는 걸 믿어봐요!",
    light: "전환, 회복, 앞으로 나아감",
    shadow: "슬픔, 아직 해결되지 않은 문제"
  },
  {
    id: 56,
    name: "소드 7",
    nameEn: "Seven of Swords",
    suit: "swords",
    number: "7",
    emoji: "🤔",
    symbol: "△",
    keywords: ["전략", "독립", "주의"],
    shortMsg: "영리하게 전략적으로 접근해봐요!",
    advice: "지금 상황에서 영리하게 행동해야 해요. 혼자 모든 걸 해결하려 하거나 몰래 행동하기보다는 솔직하게 대처하는 것이 더 좋아요. 정직이 최선의 전략이에요. 꼼수보다 진심이 훨씬 오래 가요!",
    light: "전략, 독립성, 영리함",
    shadow: "속임수, 회피"
  },
  {
    id: 57,
    name: "소드 8",
    nameEn: "Eight of Swords",
    suit: "swords",
    number: "8",
    emoji: "🙈",
    symbol: "△",
    keywords: ["속박", "두려움", "자기 제한"],
    shortMsg: "난 할 수 있어! 스스로를 믿어봐요!",
    advice: "'난 안 돼'라는 생각에 스스로 갇혀 있나요? 용기를 내면 충분히 벗어날 수 있어요. 사실 당신을 묶고 있는 건 외부의 것이 아니라 자신의 생각일 수 있어요. 작은 것 하나부터 용기를 내서 도전해봐요. 당신은 할 수 있어요!",
    light: "자유, 용기, 자기 수용",
    shadow: "자기 제한, 부정적 생각"
  },
  {
    id: 58,
    name: "소드 9",
    nameEn: "Nine of Swords",
    suit: "swords",
    number: "9",
    emoji: "😰",
    symbol: "△",
    keywords: ["불안", "걱정", "악몽"],
    shortMsg: "걱정의 대부분은 실제로 일어나지 않아요!",
    advice: "밤에 잠을 못 자거나 걱정이 너무 많나요? 머릿속 걱정의 90%는 실제로 일어나지 않아요. 지금 걱정을 종이에 적어보고, 그것이 현실인지 아닌지 따져봐요. 너무 힘들면 상담 선생님께 도움을 받아봐요. 혼자 감당하지 않아도 돼요!",
    light: "각성, 현실 직면",
    shadow: "불안, 걱정, 자기 고문"
  },
  {
    id: 59,
    name: "소드 10",
    nameEn: "Ten of Swords",
    suit: "swords",
    number: "10",
    emoji: "🌅",
    symbol: "△",
    keywords: ["끝", "변화", "새 출발"],
    shortMsg: "힘든 시간이 끝나고 새 아침이 떠요!",
    advice: "힘들었던 상황이 드디어 끝났습니다. 이제 다시 일어설 기회만 남았어요. 바닥을 쳤다면 이제 올라갈 일만 남은 거예요. 이 힘든 경험이 나를 더 강하게 만들어줄 거예요. 새로운 시작을 준비해봐요!",
    light: "끝, 새로운 시작, 회복",
    shadow: "극도의 고통, 패배감"
  },
  {
    id: 60,
    name: "페이지 소드",
    nameEn: "Page of Swords",
    suit: "swords",
    number: "P",
    emoji: "🔍",
    symbol: "△",
    keywords: ["호기심", "경계심", "소통"],
    shortMsg: "날카로운 질문으로 진실을 찾아봐요!",
    advice: "궁금한 것이 있다면 적극적으로 물어봐요. 뭔가 이상한 느낌이 든다면 그 직감을 믿고 확인해봐요. 정보를 모으고 분석하는 능력이 빛을 발하는 시기예요. 무엇이든 알고 싶다는 호기심을 잃지 마세요!",
    light: "호기심, 기민함, 소통",
    shadow: "험담, 지나친 의심"
  },
  {
    id: 61,
    name: "나이트 소드",
    nameEn: "Knight of Swords",
    suit: "swords",
    number: "N",
    emoji: "🐎",
    symbol: "△",
    keywords: ["직접적", "빠른 행동", "지성"],
    shortMsg: "생각한 것을 직접적으로 행동해봐요!",
    advice: "생각을 빠르게 행동으로 옮기는 시기예요. 하지만 너무 충동적이지 않도록 주의해요. 말이나 행동이 너무 날카로워서 주변 사람에게 상처 줄 수 있으니, 한 번 더 생각하고 표현해봐요. 열정은 좋지만 방향을 잘 잡아야 해요!",
    light: "결단력, 지성, 직접성",
    shadow: "충동성, 무모함"
  },
  {
    id: 62,
    name: "퀸 소드",
    nameEn: "Queen of Swords",
    suit: "swords",
    number: "Q",
    emoji: "👸",
    symbol: "△",
    keywords: ["독립성", "솔직함", "지성"],
    shortMsg: "냉철하고 솔직하게 판단해봐요!",
    advice: "감정보다 이성적으로 판단해야 할 때예요. 솔직하게 말하되 따뜻함을 잃지 말아요. 불필요한 것은 과감히 정리하고 내가 원하는 방향을 명확히 해봐요. 독립적이고 강한 나를 믿어봐요!",
    light: "독립성, 명확함, 지성",
    shadow: "냉정함, 지나친 비판"
  },
  {
    id: 63,
    name: "킹 소드",
    nameEn: "King of Swords",
    suit: "swords",
    number: "K",
    emoji: "🤴",
    symbol: "△",
    keywords: ["권위", "지성", "공정함"],
    shortMsg: "논리적으로 생각하고 공정하게 판단해요!",
    advice: "감정에 휩쓸리지 말고 논리적으로 생각해봐요. 규칙과 원칙을 지키는 것이 결국 나를 지키는 방법이에요. 어떤 결정을 내릴 때 사실에 기반해서 공정하게 판단해봐요. 지적인 당신이 빛날 시기예요!",
    light: "지성, 공정함, 권위",
    shadow: "냉혹함, 지나친 비판"
  },

  // ===== 마이너 아르카나 - 펜타클 (Pentacles) =====
  {
    id: 64,
    name: "에이스 펜타클",
    nameEn: "Ace of Pentacles",
    suit: "pentacles",
    number: "A",
    emoji: "🌱",
    symbol: "⬠",
    keywords: ["기회", "물질적 이득", "새로운 시작"],
    shortMsg: "새로운 기회와 실질적인 이득이 생겨요!",
    advice: "용돈이나 선물, 혹은 새로운 배움의 기회처럼 실질적인 이득이 생겨요. 좋은 기회가 왔을 때 두 손으로 잡아봐요. 새로운 것을 배우거나 도전하면 실질적인 결과로 이어질 수 있어요!",
    light: "기회, 안정, 실질적 이득",
    shadow: "놓친 기회, 물질주의"
  },
  {
    id: 65,
    name: "펜타클 2",
    nameEn: "Two of Pentacles",
    suit: "pentacles",
    number: "2",
    emoji: "🤹",
    symbol: "⬠",
    keywords: ["균형", "멀티태스킹", "적응"],
    shortMsg: "여러 가지를 균형 있게 조율해봐요!",
    advice: "공부, 친구, 취미 등 여러 가지를 동시에 잘 하려고 하고 있나요? 우선순위를 정하고 하나씩 집중해봐요. 모든 것을 완벽하게 다 잘할 수는 없어요. 가장 중요한 것에 집중하면 다른 것들도 자연스럽게 따라와요!",
    light: "적응력, 균형, 유연성",
    shadow: "불안정, 과도한 부담"
  },
  {
    id: 66,
    name: "펜타클 3",
    nameEn: "Three of Pentacles",
    suit: "pentacles",
    number: "3",
    emoji: "🤝",
    symbol: "⬠",
    keywords: ["협력", "팀워크", "학습"],
    shortMsg: "함께하면 더 좋은 결과가 나와요!",
    advice: "팀 프로젝트나 수행평가에서 협력하면 최고의 결과가 나와요. 혼자 다 하려 하지 말고 역할을 나누고 서로의 강점을 활용해봐요. 협력하는 과정에서 배울 것이 정말 많아요. 팀원을 믿고 함께 해봐요!",
    light: "협력, 학습, 성장",
    shadow: "불협화음, 개인주의"
  },
  {
    id: 67,
    name: "펜타클 4",
    nameEn: "Four of Pentacles",
    suit: "pentacles",
    number: "4",
    emoji: "🤑",
    symbol: "⬠",
    keywords: ["안정", "소유", "저축"],
    shortMsg: "나눔과 성장의 균형을 맞춰봐요!",
    advice: "안정감을 원하는 건 좋지만, 너무 꽉 쥐고 있으면 새로운 것이 들어올 자리가 없어요. 자신이 가진 것들을 나누고 새로운 경험에 열려봐요. 물질적인 것보다 경험과 관계가 더 가치 있을 때도 있어요!",
    light: "안정, 절약, 보안",
    shadow: "인색함, 변화 두려움"
  },
  {
    id: 68,
    name: "펜타클 5",
    nameEn: "Five of Pentacles",
    suit: "pentacles",
    number: "5",
    emoji: "🥶",
    symbol: "⬠",
    keywords: ["어려움", "고립", "도움 요청"],
    shortMsg: "어려울 때 도움을 요청해도 괜찮아요!",
    advice: "지금 경제적으로나 정서적으로 힘든 상황인가요? 혼자 감당하려 하지 말고 도움을 요청해봐요. 학교 상담 선생님, 부모님, 또는 청소년 상담 기관에 연락해봐요. 어려움을 솔직히 말하는 용기가 상황을 바꿀 수 있어요!",
    light: "도움 요청, 공동체, 연대",
    shadow: "결핍, 고립, 어려움"
  },
  {
    id: 69,
    name: "펜타클 6",
    nameEn: "Six of Pentacles",
    suit: "pentacles",
    number: "6",
    emoji: "🤲",
    symbol: "⬠",
    keywords: ["나눔", "관대함", "균형"],
    shortMsg: "주고받는 균형이 행복을 만들어요!",
    advice: "받는 것만큼 주는 것도 중요해요. 친구에게 작은 도움이나 응원을 줘봐요. 반대로 도움이 필요할 때는 받는 것을 부끄러워하지 마세요. 서로 주고받는 관계에서 진정한 우정이 쌓여요!",
    light: "관대함, 나눔, 균형",
    shadow: "불균형, 의존"
  },
  {
    id: 70,
    name: "펜타클 7",
    nameEn: "Seven of Pentacles",
    suit: "pentacles",
    number: "7",
    emoji: "🌾",
    symbol: "⬠",
    keywords: ["인내", "평가", "기다림"],
    shortMsg: "꾸준히 키운 것이 열매를 맺고 있어요!",
    advice: "지금까지 꾸준히 노력해온 것들이 조금씩 결과를 보여주고 있어요. 빠른 결과를 기대하기보다는 과정을 즐겨봐요. 씨앗을 심으면 열매가 맺히는 데 시간이 걸리듯, 노력도 시간이 필요해요. 기다릴 줄 아는 것도 능력이에요!",
    light: "인내, 평가, 성장",
    shadow: "조급함, 의심"
  },
  {
    id: 71,
    name: "펜타클 8",
    nameEn: "Eight of Pentacles",
    suit: "pentacles",
    number: "8",
    emoji: "⚒️",
    symbol: "⬠",
    keywords: ["노력", "기술 향상", "집중"],
    shortMsg: "꾸준한 노력이 전문가를 만들어요!",
    advice: "꾸준히 노력하는 당신의 모습이 빛나고 있어요. 곧 전문가가 될 거예요. 지금 하는 공부나 활동에 집중해봐요. 매일 조금씩이라도 연습하고 배우다 보면 어느새 실력이 크게 늘어 있을 거예요!",
    light: "집중력, 노력, 기술 향상",
    shadow: "완벽주의, 단조로움"
  },
  {
    id: 72,
    name: "펜타클 9",
    nameEn: "Nine of Pentacles",
    suit: "pentacles",
    number: "9",
    emoji: "🌺",
    symbol: "⬠",
    keywords: ["성취", "독립", "여유"],
    shortMsg: "스스로 이룬 것들을 자랑스러워해봐요!",
    advice: "그동안 쌓아온 노력과 성취를 자랑스럽게 여겨봐요. 스스로 뭔가를 해냈다는 자신감이 중요해요. 지금 가진 것들에 감사하며 여유 있게 즐겨봐요. 당신은 충분히 잘 하고 있어요!",
    light: "성취, 독립, 자기 만족",
    shadow: "자만, 고립"
  },
  {
    id: 73,
    name: "펜타클 10",
    nameEn: "Ten of Pentacles",
    suit: "pentacles",
    number: "10",
    emoji: "🏠",
    symbol: "⬠",
    keywords: ["안정", "유산", "가족"],
    shortMsg: "가족과 가까운 사람들이 큰 힘이에요!",
    advice: "가족이나 주변 사람들로부터 든든한 지지를 받을 수 있는 시기예요. 감사한 마음을 표현해봐요. 오랜 관계나 전통에서 지혜를 얻을 수도 있어요. 소중한 사람들과의 연결이 지금 가장 큰 재산이에요!",
    light: "안정, 유산, 가족, 풍요",
    shadow: "무관심, 상실"
  },
  {
    id: 74,
    name: "페이지 펜타클",
    nameEn: "Page of Pentacles",
    suit: "pentacles",
    number: "P",
    emoji: "📖",
    symbol: "⬠",
    keywords: ["학습", "새로운 기술", "목표"],
    shortMsg: "새로운 것을 배우는 최고의 시기예요!",
    advice: "새로운 기술이나 학문을 배우기 시작하면 좋은 성과를 거둘 거예요. 배우는 것을 두려워하지 말고 작은 것부터 차근차근 익혀봐요. 학교 공부든, 취미든, 새로운 무언가를 시작하기에 완벽한 때예요!",
    light: "학습, 목표 설정, 꾸준함",
    shadow: "지나친 꿈, 비현실적"
  },
  {
    id: 75,
    name: "나이트 펜타클",
    nameEn: "Knight of Pentacles",
    suit: "pentacles",
    number: "N",
    emoji: "🐎",
    symbol: "⬠",
    keywords: ["성실함", "꾸준함", "책임감"],
    shortMsg: "느리더라도 꾸준히 가는 것이 최고예요!",
    advice: "빠른 결과보다 꾸준한 노력이 중요한 시기예요. 조금 느리게 가더라도 확실하게 나아가는 것이 결국 더 멀리 가는 방법이에요. 약속을 지키고 책임감 있게 행동하면 신뢰가 쌓여요!",
    light: "성실함, 책임감, 꾸준함",
    shadow: "지나친 신중함, 융통성 부족"
  },
  {
    id: 76,
    name: "퀸 펜타클",
    nameEn: "Queen of Pentacles",
    suit: "pentacles",
    number: "Q",
    emoji: "👸",
    symbol: "⬠",
    keywords: ["돌봄", "실용성", "풍요"],
    shortMsg: "나 자신을 잘 돌보는 것이 중요해요!",
    advice: "지금 내 몸과 마음을 잘 돌보고 있나요? 규칙적인 생활, 균형 잡힌 식사, 충분한 수면이 모든 것의 기초예요. 나 자신을 소중히 대하면 주변 사람들도 그만큼 소중히 대해줄 거예요!",
    light: "돌봄, 실용성, 따뜻함",
    shadow: "과잉 보호, 물질주의"
  },
  {
    id: 77,
    name: "킹 펜타클",
    nameEn: "King of Pentacles",
    suit: "pentacles",
    number: "K",
    emoji: "🤴",
    symbol: "⬠",
    keywords: ["성공", "안정", "리더십"],
    shortMsg: "꾸준한 노력으로 목표를 이루어요!",
    advice: "현실적이고 안정적인 방식으로 목표를 이루어가는 시기예요. 꿈만 꾸지 말고 실제로 행동으로 옮겨봐요. 재정적이든 학업적이든 꾸준히 쌓아온 것들이 단단한 기반이 되어줄 거예요!",
    light: "성공, 안정, 성취, 지도력",
    shadow: "물질주의, 완고함"
  }
];

// 포지션 의미 (3카드 스프레드)
const CARD_POSITIONS = [
  {
    name: "과거의 영향",
    emoji: "🌙",
    description: "지금 고민에 영향을 준 과거의 상황이나 감정"
  },
  {
    name: "현재의 핵심",
    emoji: "⭐",
    description: "지금 이 순간 가장 중요한 메시지"
  },
  {
    name: "앞으로의 방향",
    emoji: "☀️",
    description: "앞으로 나아갈 방향과 조언"
  }
];

// 수트 정보
const SUIT_INFO = {
  major: { name: "메이저 아르카나", emoji: "🔮", color: "#9b59b6", desc: "인생의 큰 테마" },
  cups: { name: "컵 수트", emoji: "💧", color: "#3498db", desc: "감정·우정·관계" },
  wands: { name: "완드 수트", emoji: "🔥", color: "#e74c3c", desc: "열정·행동·도전" },
  swords: { name: "소드 수트", emoji: "⚔️", color: "#95a5a6", desc: "생각·결정·소통" },
  pentacles: { name: "펜타클 수트", emoji: "🌱", color: "#27ae60", desc: "노력·성과·현실" }
};
